#!/usr/bin/env python

import argparse, sys

class Cutter() :
    def __init__(self,fields,delimiter="\t",spacer="\t"):
        self.fields = fields
        self.delimiter = delimiter
        self.spacer = spacer

    def printFields(self,line,output=sys.stdout):

        line = line.split(self.delimiter)
        print line

        lineNum = 0
        for field in self.fields :
            lineNum += 1
            if lineNum > 0 :
                output.write(self.spacer)

            try :

                index = int(field)
                try :
                    output.write(line[index])
                except IndexError :
                    output.write("<NONE>")

            except ValueError :
                output.write(field)

        output.write("\n")

def main() :
    parser = argparse.ArgumentParser(description="Remove and/or rearrange "
        + "sections from each line of a file(s).")
    parser.add_argument('-f',"--fields", action='store',default=[], nargs='+',
        help="Fields to select")
    parser.add_argument('-d',"--delimiter", action='store',default="\t",
        help="Sets field delimiter(default is TAB)")

    parsed = parser.parse_args(sys.argv[1:])
    cutter = Cutter(parsed.fields, parsed.delimiter)
    print parsed

    for line in sys.stdin :
        cutter.printFields(line)


if __name__ == '__main__':
    main()
